#!/usr/bin/env python
import dom_server as server
import json


sample_request_data = {
        "weights": [1, 0, -1, 1],
        "rows": [
            [2, 3, 4, 5],
            [4, 6, 2, 6],
            [5, 6, 2, 6],
            [4, 6, 7, 2]]
        }

dom_scores, response_code = server.mock_request(
        "POST", "domScoredData", json.dumps(sample_request_data))

if response_code != 200:
    print("Error response: " + dom_scores)
else:
    print(json.loads(dom_scores))
