#!/usr/bin/env bash

pathadd() {
    	if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        	PATH="${PATH:+"$PATH:"}$1"
    	fi
}
pathadd $Bin

ok() {
  (cd ../test; $Lua $1.lua)
}

htmls() {
  cd ../src
  pycco -i -d ../docs *.lua
}
gitready() {
	git config --global credential.helper 'cache --timeout 3600'
}
push() {
	gitready
	git commit -am saving
	git push
	git status
}
pull() {
	gitready
	git pull
}
#--- tag line stuff
_c1="\[\033[01;32m\]"
_c2="\[\033[01;34m\]"
_c3="\[\033[31m\]"
_c6="\033[33m"
_c5="\[\033[35m\]$"
_c0="\[\033[00m\]"
_c7="[\033]01;19\]"

here() { cd $1; basename "$PWD"; }

PROMPT_COMMAND='echo -ne "${_c6}${What}:$(git branch 2>/dev/null | grep '^*' | colrm 1 2)> \033]0;$(here ../..)/$(here ..)/$(here .)\007";PS1="${_c1}$(here ../..)/$_c2$(here ..)/$_c3$(here .) ${_c6}\!>${_c0}\e[m "'

alias ll='ls -GF'

alias vi="`which vim` -u $Tmp/.vimrc "
alias cols="column -s, -t"
cd $Src
